package model;
// Generated May 14, 2015 12:58:39 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cihaz generated by hbm2java
 */
public class Cihaz  implements java.io.Serializable {


     private Integer cihazId;
     private String macAdresi;
     private Date eklenmeTarihi;
     private boolean isAktif;
     private Set<Log> logs = new HashSet<Log>(0);

    public Cihaz() {
    }

	
    public Cihaz(String macAdresi, Date eklenmeTarihi, boolean isAktif) {
        this.macAdresi = macAdresi;
        this.eklenmeTarihi = eklenmeTarihi;
        this.isAktif = isAktif;
    }
    public Cihaz(String macAdresi, Date eklenmeTarihi, boolean isAktif, Set<Log> logs) {
       this.macAdresi = macAdresi;
       this.eklenmeTarihi = eklenmeTarihi;
       this.isAktif = isAktif;
       this.logs = logs;
    }
   
    public Integer getCihazId() {
        return this.cihazId;
    }
    
    public void setCihazId(Integer cihazId) {
        this.cihazId = cihazId;
    }
    public String getMacAdresi() {
        return this.macAdresi;
    }
    
    public void setMacAdresi(String macAdresi) {
        this.macAdresi = macAdresi;
    }
    public Date getEklenmeTarihi() {
        return this.eklenmeTarihi;
    }
    
    public void setEklenmeTarihi(Date eklenmeTarihi) {
        this.eklenmeTarihi = eklenmeTarihi;
    }
    public boolean isIsAktif() {
        return this.isAktif;
    }
    
    public void setIsAktif(boolean isAktif) {
        this.isAktif = isAktif;
    }
    public Set<Log> getLogs() {
        return this.logs;
    }
    
    public void setLogs(Set<Log> logs) {
        this.logs = logs;
    }




}


