package model;
// Generated May 14, 2015 12:58:39 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DigerGider generated by hbm2java
 */
public class DigerGider  implements java.io.Serializable {


     private Integer digerGiderId;
     private String adi;
     private Float miktari;
     private String aciklama;
     private Date alisTarihi;
     private Boolean isAktif;
     private Set<Gider> giders = new HashSet<Gider>(0);

    public DigerGider() {
    }

    public DigerGider(String adi, Float miktari, String aciklama, Date alisTarihi, Boolean isAktif, Set<Gider> giders) {
       this.adi = adi;
       this.miktari = miktari;
       this.aciklama = aciklama;
       this.alisTarihi = alisTarihi;
       this.isAktif = isAktif;
       this.giders = giders;
    }
   
    public Integer getDigerGiderId() {
        return this.digerGiderId;
    }
    
    public void setDigerGiderId(Integer digerGiderId) {
        this.digerGiderId = digerGiderId;
    }
    public String getAdi() {
        return this.adi;
    }
    
    public void setAdi(String adi) {
        this.adi = adi;
    }
    public Float getMiktari() {
        return this.miktari;
    }
    
    public void setMiktari(Float miktari) {
        this.miktari = miktari;
    }
    public String getAciklama() {
        return this.aciklama;
    }
    
    public void setAciklama(String aciklama) {
        this.aciklama = aciklama;
    }
    public Date getAlisTarihi() {
        return this.alisTarihi;
    }
    
    public void setAlisTarihi(Date alisTarihi) {
        this.alisTarihi = alisTarihi;
    }
    public Boolean getIsAktif() {
        return this.isAktif;
    }
    
    public void setIsAktif(Boolean isAktif) {
        this.isAktif = isAktif;
    }
    public Set<Gider> getGiders() {
        return this.giders;
    }
    
    public void setGiders(Set<Gider> giders) {
        this.giders = giders;
    }




}


