package model;
// Generated May 14, 2015 12:58:39 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Gelir generated by hbm2java
 */
public class Gelir  implements java.io.Serializable {


     private Integer gelirId;
     private float miktar;
     private Date tarih;
     private boolean isAktif;
     private Set<Masa> masas = new HashSet<Masa>(0);

    public Gelir() {
    }

	
    public Gelir(float miktar, Date tarih, boolean isAktif) {
        this.miktar = miktar;
        this.tarih = tarih;
        this.isAktif = isAktif;
    }
    public Gelir(float miktar, Date tarih, boolean isAktif, Set<Masa> masas) {
       this.miktar = miktar;
       this.tarih = tarih;
       this.isAktif = isAktif;
       this.masas = masas;
    }
   
    public Integer getGelirId() {
        return this.gelirId;
    }
    
    public void setGelirId(Integer gelirId) {
        this.gelirId = gelirId;
    }
    public float getMiktar() {
        return this.miktar;
    }
    
    public void setMiktar(float miktar) {
        this.miktar = miktar;
    }
    public Date getTarih() {
        return this.tarih;
    }
    
    public void setTarih(Date tarih) {
        this.tarih = tarih;
    }
    public boolean isIsAktif() {
        return this.isAktif;
    }
    
    public void setIsAktif(boolean isAktif) {
        this.isAktif = isAktif;
    }
    public Set<Masa> getMasas() {
        return this.masas;
    }
    
    public void setMasas(Set<Masa> masas) {
        this.masas = masas;
    }




}


