package model;
// Generated May 14, 2015 12:58:39 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * GiderTuru generated by hbm2java
 */
public class GiderTuru  implements java.io.Serializable {


     private Integer giderTuruId;
     private String adi;
     private Boolean isAktif;
     private Set<Gider> giders = new HashSet<Gider>(0);

    public GiderTuru() {
    }

    public GiderTuru(String adi, Boolean isAktif, Set<Gider> giders) {
       this.adi = adi;
       this.isAktif = isAktif;
       this.giders = giders;
    }
   
    public Integer getGiderTuruId() {
        return this.giderTuruId;
    }
    
    public void setGiderTuruId(Integer giderTuruId) {
        this.giderTuruId = giderTuruId;
    }
    public String getAdi() {
        return this.adi;
    }
    
    public void setAdi(String adi) {
        this.adi = adi;
    }
    public Boolean getIsAktif() {
        return this.isAktif;
    }
    
    public void setIsAktif(Boolean isAktif) {
        this.isAktif = isAktif;
    }
    public Set<Gider> getGiders() {
        return this.giders;
    }
    
    public void setGiders(Set<Gider> giders) {
        this.giders = giders;
    }




}


