package model;
// Generated May 14, 2015 12:58:39 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Gider generated by hbm2java
 */
public class Gider  implements java.io.Serializable {


     private Integer giderId;
     private DigerGider digerGider;
     private GiderTuru giderTuru;
     private Stok stok;
     private float miktar;
     private Date alisTarihi;
     private boolean isAktif;

    public Gider() {
    }

	
    public Gider(GiderTuru giderTuru, float miktar, Date alisTarihi, boolean isAktif) {
        this.giderTuru = giderTuru;
        this.miktar = miktar;
        this.alisTarihi = alisTarihi;
        this.isAktif = isAktif;
    }
    public Gider(DigerGider digerGider, GiderTuru giderTuru, Stok stok, float miktar, Date alisTarihi, boolean isAktif) {
       this.digerGider = digerGider;
       this.giderTuru = giderTuru;
       this.stok = stok;
       this.miktar = miktar;
       this.alisTarihi = alisTarihi;
       this.isAktif = isAktif;
    }
   
    public Integer getGiderId() {
        return this.giderId;
    }
    
    public void setGiderId(Integer giderId) {
        this.giderId = giderId;
    }
    public DigerGider getDigerGider() {
        return this.digerGider;
    }
    
    public void setDigerGider(DigerGider digerGider) {
        this.digerGider = digerGider;
    }
    public GiderTuru getGiderTuru() {
        return this.giderTuru;
    }
    
    public void setGiderTuru(GiderTuru giderTuru) {
        this.giderTuru = giderTuru;
    }
    public Stok getStok() {
        return this.stok;
    }
    
    public void setStok(Stok stok) {
        this.stok = stok;
    }
    public float getMiktar() {
        return this.miktar;
    }
    
    public void setMiktar(float miktar) {
        this.miktar = miktar;
    }
    public Date getAlisTarihi() {
        return this.alisTarihi;
    }
    
    public void setAlisTarihi(Date alisTarihi) {
        this.alisTarihi = alisTarihi;
    }
    public boolean isIsAktif() {
        return this.isAktif;
    }
    
    public void setIsAktif(boolean isAktif) {
        this.isAktif = isAktif;
    }




}


