package model;
// Generated May 14, 2015 12:58:39 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Kampanya generated by hbm2java
 */
public class Kampanya  implements java.io.Serializable {


     private int kampanyaId;
     private String kampanyaAd;
     private String kampanyaKod;
     private Float indirimOrani;
     private Float indirimMiktari;
     private boolean isKullanildi;
     private boolean isAktif;
     private Set<Masa> masas = new HashSet<Masa>(0);

    public Kampanya() {
    }

	
    public Kampanya(int kampanyaId, String kampanyaAd, String kampanyaKod, boolean isKullanildi, boolean isAktif) {
        this.kampanyaId = kampanyaId;
        this.kampanyaAd = kampanyaAd;
        this.kampanyaKod = kampanyaKod;
        this.isKullanildi = isKullanildi;
        this.isAktif = isAktif;
    }
    public Kampanya(int kampanyaId, String kampanyaAd, String kampanyaKod, Float indirimOrani, Float indirimMiktari, boolean isKullanildi, boolean isAktif, Set<Masa> masas) {
       this.kampanyaId = kampanyaId;
       this.kampanyaAd = kampanyaAd;
       this.kampanyaKod = kampanyaKod;
       this.indirimOrani = indirimOrani;
       this.indirimMiktari = indirimMiktari;
       this.isKullanildi = isKullanildi;
       this.isAktif = isAktif;
       this.masas = masas;
    }
   
    public int getKampanyaId() {
        return this.kampanyaId;
    }
    
    public void setKampanyaId(int kampanyaId) {
        this.kampanyaId = kampanyaId;
    }
    public String getKampanyaAd() {
        return this.kampanyaAd;
    }
    
    public void setKampanyaAd(String kampanyaAd) {
        this.kampanyaAd = kampanyaAd;
    }
    public String getKampanyaKod() {
        return this.kampanyaKod;
    }
    
    public void setKampanyaKod(String kampanyaKod) {
        this.kampanyaKod = kampanyaKod;
    }
    public Float getIndirimOrani() {
        return this.indirimOrani;
    }
    
    public void setIndirimOrani(Float indirimOrani) {
        this.indirimOrani = indirimOrani;
    }
    public Float getIndirimMiktari() {
        return this.indirimMiktari;
    }
    
    public void setIndirimMiktari(Float indirimMiktari) {
        this.indirimMiktari = indirimMiktari;
    }
    public boolean isIsKullanildi() {
        return this.isKullanildi;
    }
    
    public void setIsKullanildi(boolean isKullanildi) {
        this.isKullanildi = isKullanildi;
    }
    public boolean isIsAktif() {
        return this.isAktif;
    }
    
    public void setIsAktif(boolean isAktif) {
        this.isAktif = isAktif;
    }
    public Set<Masa> getMasas() {
        return this.masas;
    }
    
    public void setMasas(Set<Masa> masas) {
        this.masas = masas;
    }




}


