package model;
// Generated May 14, 2015 12:58:39 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * LogDurum generated by hbm2java
 */
public class LogDurum  implements java.io.Serializable {


     private Integer logDurumId;
     private String durumAd;
     private boolean isAktif;
     private Set<Log> logs = new HashSet<Log>(0);

    public LogDurum() {
    }

	
    public LogDurum(boolean isAktif) {
        this.isAktif = isAktif;
    }
    public LogDurum(String durumAd, boolean isAktif, Set<Log> logs) {
       this.durumAd = durumAd;
       this.isAktif = isAktif;
       this.logs = logs;
    }
   
    public Integer getLogDurumId() {
        return this.logDurumId;
    }
    
    public void setLogDurumId(Integer logDurumId) {
        this.logDurumId = logDurumId;
    }
    public String getDurumAd() {
        return this.durumAd;
    }
    
    public void setDurumAd(String durumAd) {
        this.durumAd = durumAd;
    }
    public boolean isIsAktif() {
        return this.isAktif;
    }
    
    public void setIsAktif(boolean isAktif) {
        this.isAktif = isAktif;
    }
    public Set<Log> getLogs() {
        return this.logs;
    }
    
    public void setLogs(Set<Log> logs) {
        this.logs = logs;
    }




}


