package model;
// Generated May 14, 2015 12:58:39 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Masa generated by hbm2java
 */
public class Masa  implements java.io.Serializable {


     private Integer masaId;
     private Gelir gelir;
     private Kampanya kampanya;
     private MasaNo masaNo;
     private Float toplamTutar;
     private Boolean isKampanya;
     private boolean isAktif;
     private boolean isOdendi;
     private Set<Siparis> siparises = new HashSet<Siparis>(0);

    public Masa() {
    }

	
    public Masa(boolean isAktif, boolean isOdendi) {
        this.isAktif = isAktif;
        this.isOdendi = isOdendi;
    }
    public Masa(Gelir gelir, Kampanya kampanya, MasaNo masaNo, Float toplamTutar, Boolean isKampanya, boolean isAktif, boolean isOdendi, Set<Siparis> siparises) {
       this.gelir = gelir;
       this.kampanya = kampanya;
       this.masaNo = masaNo;
       this.toplamTutar = toplamTutar;
       this.isKampanya = isKampanya;
       this.isAktif = isAktif;
       this.isOdendi = isOdendi;
       this.siparises = siparises;
    }
   
    public Integer getMasaId() {
        return this.masaId;
    }
    
    public void setMasaId(Integer masaId) {
        this.masaId = masaId;
    }
    public Gelir getGelir() {
        return this.gelir;
    }
    
    public void setGelir(Gelir gelir) {
        this.gelir = gelir;
    }
    public Kampanya getKampanya() {
        return this.kampanya;
    }
    
    public void setKampanya(Kampanya kampanya) {
        this.kampanya = kampanya;
    }
    public MasaNo getMasaNo() {
        return this.masaNo;
    }
    
    public void setMasaNo(MasaNo masaNo) {
        this.masaNo = masaNo;
    }
    public Float getToplamTutar() {
        return this.toplamTutar;
    }
    
    public void setToplamTutar(Float toplamTutar) {
        this.toplamTutar = toplamTutar;
    }
    public Boolean getIsKampanya() {
        return this.isKampanya;
    }
    
    public void setIsKampanya(Boolean isKampanya) {
        this.isKampanya = isKampanya;
    }
    public boolean isIsAktif() {
        return this.isAktif;
    }
    
    public void setIsAktif(boolean isAktif) {
        this.isAktif = isAktif;
    }
    public boolean isIsOdendi() {
        return this.isOdendi;
    }
    
    public void setIsOdendi(boolean isOdendi) {
        this.isOdendi = isOdendi;
    }
    public Set<Siparis> getSiparises() {
        return this.siparises;
    }
    
    public void setSiparises(Set<Siparis> siparises) {
        this.siparises = siparises;
    }




}


