package model;
// Generated May 14, 2015 12:58:39 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * MasaNo generated by hbm2java
 */
public class MasaNo  implements java.io.Serializable {


     private Integer masaNoId;
     private int numara;
     private Boolean isAktif;
     private Set<Masa> masas = new HashSet<Masa>(0);

    public MasaNo() {
    }

	
    public MasaNo(int numara) {
        this.numara = numara;
    }
    public MasaNo(int numara, Boolean isAktif, Set<Masa> masas) {
       this.numara = numara;
       this.isAktif = isAktif;
       this.masas = masas;
    }
   
    public Integer getMasaNoId() {
        return this.masaNoId;
    }
    
    public void setMasaNoId(Integer masaNoId) {
        this.masaNoId = masaNoId;
    }
    public int getNumara() {
        return this.numara;
    }
    
    public void setNumara(int numara) {
        this.numara = numara;
    }
    public Boolean getIsAktif() {
        return this.isAktif;
    }
    
    public void setIsAktif(Boolean isAktif) {
        this.isAktif = isAktif;
    }
    public Set<Masa> getMasas() {
        return this.masas;
    }
    
    public void setMasas(Set<Masa> masas) {
        this.masas = masas;
    }




}


