package model;
// Generated May 14, 2015 12:58:39 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Stok generated by hbm2java
 */
public class Stok  implements java.io.Serializable {


     private Integer stokId;
     private Firma firma;
     private Personel personel;
     private Urun urun;
     private int alinanAdet;
     private int kalanAdet;
     private float alisFiyati;
     private Date alisTarihi;
     private boolean isAktif;
     private Set<Gider> giders = new HashSet<Gider>(0);
     private Set<Siparis> siparises = new HashSet<Siparis>(0);

    public Stok() {
    }

	
    public Stok(Firma firma, Personel personel, Urun urun, int alinanAdet, int kalanAdet, float alisFiyati, Date alisTarihi, boolean isAktif) {
        this.firma = firma;
        this.personel = personel;
        this.urun = urun;
        this.alinanAdet = alinanAdet;
        this.kalanAdet = kalanAdet;
        this.alisFiyati = alisFiyati;
        this.alisTarihi = alisTarihi;
        this.isAktif = isAktif;
    }
    public Stok(Firma firma, Personel personel, Urun urun, int alinanAdet, int kalanAdet, float alisFiyati, Date alisTarihi, boolean isAktif, Set<Gider> giders, Set<Siparis> siparises) {
       this.firma = firma;
       this.personel = personel;
       this.urun = urun;
       this.alinanAdet = alinanAdet;
       this.kalanAdet = kalanAdet;
       this.alisFiyati = alisFiyati;
       this.alisTarihi = alisTarihi;
       this.isAktif = isAktif;
       this.giders = giders;
       this.siparises = siparises;
    }
   
    public Integer getStokId() {
        return this.stokId;
    }
    
    public void setStokId(Integer stokId) {
        this.stokId = stokId;
    }
    public Firma getFirma() {
        return this.firma;
    }
    
    public void setFirma(Firma firma) {
        this.firma = firma;
    }
    public Personel getPersonel() {
        return this.personel;
    }
    
    public void setPersonel(Personel personel) {
        this.personel = personel;
    }
    public Urun getUrun() {
        return this.urun;
    }
    
    public void setUrun(Urun urun) {
        this.urun = urun;
    }
    public int getAlinanAdet() {
        return this.alinanAdet;
    }
    
    public void setAlinanAdet(int alinanAdet) {
        this.alinanAdet = alinanAdet;
    }
    public int getKalanAdet() {
        return this.kalanAdet;
    }
    
    public void setKalanAdet(int kalanAdet) {
        this.kalanAdet = kalanAdet;
    }
    public float getAlisFiyati() {
        return this.alisFiyati;
    }
    
    public void setAlisFiyati(float alisFiyati) {
        this.alisFiyati = alisFiyati;
    }
    public Date getAlisTarihi() {
        return this.alisTarihi;
    }
    
    public void setAlisTarihi(Date alisTarihi) {
        this.alisTarihi = alisTarihi;
    }
    public boolean isIsAktif() {
        return this.isAktif;
    }
    
    public void setIsAktif(boolean isAktif) {
        this.isAktif = isAktif;
    }
    public Set<Gider> getGiders() {
        return this.giders;
    }
    
    public void setGiders(Set<Gider> giders) {
        this.giders = giders;
    }
    public Set<Siparis> getSiparises() {
        return this.siparises;
    }
    
    public void setSiparises(Set<Siparis> siparises) {
        this.siparises = siparises;
    }




}


