package model;
// Generated May 14, 2015 12:58:39 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tablo generated by hbm2java
 */
public class Tablo  implements java.io.Serializable {


     private Integer tabloId;
     private String tabloAdi;
     private boolean isAktif;
     private Set<Log> logs = new HashSet<Log>(0);

    public Tablo() {
    }

	
    public Tablo(boolean isAktif) {
        this.isAktif = isAktif;
    }
    public Tablo(String tabloAdi, boolean isAktif, Set<Log> logs) {
       this.tabloAdi = tabloAdi;
       this.isAktif = isAktif;
       this.logs = logs;
    }
   
    public Integer getTabloId() {
        return this.tabloId;
    }
    
    public void setTabloId(Integer tabloId) {
        this.tabloId = tabloId;
    }
    public String getTabloAdi() {
        return this.tabloAdi;
    }
    
    public void setTabloAdi(String tabloAdi) {
        this.tabloAdi = tabloAdi;
    }
    public boolean isIsAktif() {
        return this.isAktif;
    }
    
    public void setIsAktif(boolean isAktif) {
        this.isAktif = isAktif;
    }
    public Set<Log> getLogs() {
        return this.logs;
    }
    
    public void setLogs(Set<Log> logs) {
        this.logs = logs;
    }




}


