package model;
// Generated May 14, 2015 12:58:39 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UrunTur generated by hbm2java
 */
public class UrunTur  implements java.io.Serializable {


     private Integer urunTurId;
     private String turAdi;
     private boolean isAktif;
     private Integer ustTur;
     private Boolean isAlt;
     private Set<Urun> uruns = new HashSet<Urun>(0);

    public UrunTur() {
    }

	
    public UrunTur(String turAdi, boolean isAktif) {
        this.turAdi = turAdi;
        this.isAktif = isAktif;
    }
    public UrunTur(String turAdi, boolean isAktif, Integer ustTur, Boolean isAlt, Set<Urun> uruns) {
       this.turAdi = turAdi;
       this.isAktif = isAktif;
       this.ustTur = ustTur;
       this.isAlt = isAlt;
       this.uruns = uruns;
    }
   
    public Integer getUrunTurId() {
        return this.urunTurId;
    }
    
    public void setUrunTurId(Integer urunTurId) {
        this.urunTurId = urunTurId;
    }
    public String getTurAdi() {
        return this.turAdi;
    }
    
    public void setTurAdi(String turAdi) {
        this.turAdi = turAdi;
    }
    public boolean isIsAktif() {
        return this.isAktif;
    }
    
    public void setIsAktif(boolean isAktif) {
        this.isAktif = isAktif;
    }
    public Integer getUstTur() {
        return this.ustTur;
    }
    
    public void setUstTur(Integer ustTur) {
        this.ustTur = ustTur;
    }
    public Boolean getIsAlt() {
        return this.isAlt;
    }
    
    public void setIsAlt(Boolean isAlt) {
        this.isAlt = isAlt;
    }
    public Set<Urun> getUruns() {
        return this.uruns;
    }
    
    public void setUruns(Set<Urun> uruns) {
        this.uruns = uruns;
    }




}


