package model;
// Generated May 14, 2015 12:58:39 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Urun generated by hbm2java
 */
public class Urun  implements java.io.Serializable {


     private Integer urunId;
     private UrunTur urunTur;
     private String urunAd;
     private int toplamAdet;
     private float satisFiyati;
     private boolean isAktif;
     private boolean isSatis;
     private String aciklama;
     private String hazirlanmaSuresi;
     private Set<Stok> stoks = new HashSet<Stok>(0);

    public Urun() {
    }

	
    public Urun(UrunTur urunTur, String urunAd, int toplamAdet, float satisFiyati, boolean isAktif, boolean isSatis) {
        this.urunTur = urunTur;
        this.urunAd = urunAd;
        this.toplamAdet = toplamAdet;
        this.satisFiyati = satisFiyati;
        this.isAktif = isAktif;
        this.isSatis = isSatis;
    }
    public Urun(UrunTur urunTur, String urunAd, int toplamAdet, float satisFiyati, boolean isAktif, boolean isSatis, String aciklama, String hazirlanmaSuresi, Set<Stok> stoks) {
       this.urunTur = urunTur;
       this.urunAd = urunAd;
       this.toplamAdet = toplamAdet;
       this.satisFiyati = satisFiyati;
       this.isAktif = isAktif;
       this.isSatis = isSatis;
       this.aciklama = aciklama;
       this.hazirlanmaSuresi = hazirlanmaSuresi;
       this.stoks = stoks;
    }
   
    public Integer getUrunId() {
        return this.urunId;
    }
    
    public void setUrunId(Integer urunId) {
        this.urunId = urunId;
    }
    public UrunTur getUrunTur() {
        return this.urunTur;
    }
    
    public void setUrunTur(UrunTur urunTur) {
        this.urunTur = urunTur;
    }
    public String getUrunAd() {
        return this.urunAd;
    }
    
    public void setUrunAd(String urunAd) {
        this.urunAd = urunAd;
    }
    public int getToplamAdet() {
        return this.toplamAdet;
    }
    
    public void setToplamAdet(int toplamAdet) {
        this.toplamAdet = toplamAdet;
    }
    public float getSatisFiyati() {
        return this.satisFiyati;
    }
    
    public void setSatisFiyati(float satisFiyati) {
        this.satisFiyati = satisFiyati;
    }
    public boolean isIsAktif() {
        return this.isAktif;
    }
    
    public void setIsAktif(boolean isAktif) {
        this.isAktif = isAktif;
    }
    public boolean isIsSatis() {
        return this.isSatis;
    }
    
    public void setIsSatis(boolean isSatis) {
        this.isSatis = isSatis;
    }
    public String getAciklama() {
        return this.aciklama;
    }
    
    public void setAciklama(String aciklama) {
        this.aciklama = aciklama;
    }
    public String getHazirlanmaSuresi() {
        return this.hazirlanmaSuresi;
    }
    
    public void setHazirlanmaSuresi(String hazirlanmaSuresi) {
        this.hazirlanmaSuresi = hazirlanmaSuresi;
    }
    public Set<Stok> getStoks() {
        return this.stoks;
    }
    
    public void setStoks(Set<Stok> stoks) {
        this.stoks = stoks;
    }




}


