package model;
// Generated May 14, 2015 12:58:39 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Yetki generated by hbm2java
 */
public class Yetki  implements java.io.Serializable {


     private Integer yetkiId;
     private String yetkiAd;
     private int derece;
     private boolean isAktif;
     private Set<Personel> personels = new HashSet<Personel>(0);

    public Yetki() {
    }

	
    public Yetki(String yetkiAd, int derece, boolean isAktif) {
        this.yetkiAd = yetkiAd;
        this.derece = derece;
        this.isAktif = isAktif;
    }
    public Yetki(String yetkiAd, int derece, boolean isAktif, Set<Personel> personels) {
       this.yetkiAd = yetkiAd;
       this.derece = derece;
       this.isAktif = isAktif;
       this.personels = personels;
    }
   
    public Integer getYetkiId() {
        return this.yetkiId;
    }
    
    public void setYetkiId(Integer yetkiId) {
        this.yetkiId = yetkiId;
    }
    public String getYetkiAd() {
        return this.yetkiAd;
    }
    
    public void setYetkiAd(String yetkiAd) {
        this.yetkiAd = yetkiAd;
    }
    public int getDerece() {
        return this.derece;
    }
    
    public void setDerece(int derece) {
        this.derece = derece;
    }
    public boolean isIsAktif() {
        return this.isAktif;
    }
    
    public void setIsAktif(boolean isAktif) {
        this.isAktif = isAktif;
    }
    public Set<Personel> getPersonels() {
        return this.personels;
    }
    
    public void setPersonels(Set<Personel> personels) {
        this.personels = personels;
    }




}


